# Generated by Django 2.2.7 on 2019-11-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_up_game_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('FC', 'Full Court: 5 vs 5'), ('HC', 'Half Court: 3 vs 3'), ('SA', 'Shoot Around')], max_length=2)),
            ],
        ),
    ]
