# Generated by Django 2.2.7 on 2019-11-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_up_game_app', '0005_auto_20191106_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='player',
            field=models.ManyToManyField(to='pick_up_game_app.Player'),
        ),
    ]
