# Generated by Django 2.2.7 on 2019-11-12 03:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pick_up_game_app', '0009_auto_20191107_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
